name: Centralized Slack Notification

on: 
  workflow_dispatch:
    inputs:
      repositoryName:
        required: true
        description: 'Name of the repository'
      commits:
        required: true
        description: 'List of recent commits'

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack via Webhook
        run: |
          IFS=$'\n' read -r -a commit_array <<< "${{ github.event.inputs.commits }}"
          commits_formatted=""
          for i in "${!commit_array[@]}"; do
            commit="${commit_array[$i]}"
            if [[ $i -lt $((${#commit_array[@]} - 1)) ]]; then
              commits_formatted+="• $commit\n"
            else
              commits_formatted+="• $commit"
            fi
          done
          JSON_PAYLOAD=$(jq -n \
                          --arg repoName "${{ github.event.inputs.repositoryName }}" \
                          --arg commits "$commits_formatted" \
                          '{
                            "blocks": [
                              {
                                "type": "section",
                                "text": {
                                  "type": "mrkdwn",
                                  "text": "*El deploy del repositorio* `<\($repoName)>` *ha sido exitoso! Estos son sus commits:*"
                                }
                              },
                              {
                                "type": "section",
                                "text": {
                                  "type": "mrkdwn",
                                  "text": "\($commits)"
                                }
                              }
                            ]
                          }')
          curl -X POST -H 'Content-type: application/json' --data "$JSON_PAYLOAD" ${{ secrets.WEBHOOK_URL }}
